name: CI/CD InfoLine

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build backend
      run: |
        echo "Build backend API"

    - name: Test backend
      run: |
        echo "Run backend tests"

    - name: Build frontend
      run: |
        echo "Build frontend Angular"

    - name: Package applications
      run: |
        echo "Packaging applications for deployment"
